### PR TITLE
Rename Nokia to MixRadio and fix test bat files

### PR DESCRIPTION
**Pull request by tOmoness**
- Root namespace of shared code projects renamed from `Nokia.Music.TestApp` to `MixRadio.TestApp`.
- Renamed references of projects from `Nokia.Music.PCL` to `MixRadio`.
- Fixed test bat files.

### CODE REVIEW

**Comment by tOmoness** [comment]
@srgb I noticed after submitting this there were a few AssemblyInfo.cs files in the test projects that still use old library and company names. I can change those and submit for review if you like?

**Comment by srgb** [comment]
Thanks, probably best to leave it for now please - I think it's a sync problem where we have a separate copy of the codebase internally - i.e. the test batch files do work internally, I'm not that shoddy(!), but they haven't gone into this repo properly. I need to check and probably push a change up fixing the other problems.
Cheers,
Steve

**Comment by tOmoness** [comment]
:+1:

**Comment by srgb** [comment]
I've done some clean up, hopefully that's the lot now. Thanks again!

**Pull request merged**
